services:
  pg_database:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi_data
    volumes:
<<<<<<< HEAD
      - "D:/other/project/data-engineering/docker/ny_taxi_postgres_data:/var/lib/postgresql/data"
=======
      - "/home/sinatavakoli2022/data-engineering/docker/ny_taxi_postgres_data:/var/lib/postgresql/data"
>>>>>>> 5c14aa08b5c5b01ad57472bbb74402dceadcb649
    ports:
      - '5432:5432'

  pg_admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '8080:80'
